### ISSUE TITLE
Our individual fish data with ages < aged fish data

### ISSUE THREAD

**Issue by hkundel** [hkundel/CASC_Fish_Climate#9]
Even when we only look at aged fish from the gears we have effort data for, and filter for the years. 

Individual fish data (1968 though 2022, only reliable through 2020)

First aged fish in individual fish data is 1986

**Comment by hkundel** [comment]
Could be river fish. The individual fish file did NOT have any rivers (no kittles). 

But with aged fish, there are rivers!!!

**Comment by mrverhoeven** [comment]
Is this a MN data problem?

**Comment by mrverhoeven** [comment]
This issue was resolved with the data request from DNR completed 23 Aug 2023 (implemented in the code in this repo mid-Sep 2023).
